### ISSUE TITLE
G8 template

### ISSUE THREAD

**Issue by ubaldop** [sake92/hepek-starter#3]
Has this repo the same scope of a Gieter8 template? If so, did you consider to write also a g8 repo for hepek?

**Comment by sake92** [comment]
@P3trur0 
Yes, kind of... I think a separate G8 repo would be better since it requires a specific folder layout.  
I made a repo for it here: https://github.com/sake92/hepek-starter.g8  
Most of G8 templates have that naming format.

You can ping me on gitter if you have any questions or help with anything. 🙂

**Comment by sake92** [comment]
Done in https://github.com/sake92/hepek-starter.g8/pull/1 🎉
